# Generated by Django 4.1.13 on 2024-07-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("company", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("quantity", models.CharField(max_length=100)),
            ],
        ),
    ]
